### ISSUE TITLE
$db->lastInsertId() return 0

### ISSUE THREAD

**Issue by raisiqueira** [lincanbin/PHP-PDO-MySQL-Class#1]

**Comment by lincanbin** [comment]
The existence of the auto_increase column in the table?

**Comment by lincanbin** [comment]
Sorry, it seems my mistake in ReadMe.
It's```$DB->lastInsertId()```, not ```$db->lastInsertId()```. 
[commit](https://github.com/lincanbin/PHP-PDO-MySQL-Class/commit/436ed738b2886b553d373c91ad4c16cfcb8e7839)

**Comment by lincanbin** [comment]
I wrote a Demo: https://github.com/lincanbin/PHP-PDO-MySQL-Class/blob/master/demo.php
