### ISSUE TITLE
PDO.class.php  broken ?

### ISSUE THREAD

**Issue by darkworks** [lincanbin/PHP-PDO-MySQL-Class#14]
i was using old version of PDO.class.php  , just copied fresh copy of PDO.class.php and replaced my old one with it , and noticed i started getting 500 error. then reverted back .

please check

**Comment by lincanbin** [comment]
error log?

**Comment by darkworks** [comment]
its fixed now ,not sure what cause it .  by the way you have my waifu Ren Tohaska picture on your profile LOL
