### ISSUE TITLE
INSERT or UPDATE if exists

### ISSUE THREAD

**Issue by HeberPcL** [lincanbin/PHP-PDO-MySQL-Class#16]
There is a need to INSERT or UPDATE values if they exist.

```
INSERT INTO TABLE (id, name, age) VALUES (1, "A", 19), (2, "B", 17), (3, "C", 22)
ON DUPLICATE KEY UPDATE
    age = 20;
```

**Comment by lincanbin** [comment]
$DB->query("");

**Comment by marcus-hiles** [comment]
@HeberPcL does the query give you an error when you execute it, and what error? Cause at a glance this query is supposed to work.
