### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user 'xxx'@'localhost' (using password: YES

### ISSUE THREAD

**Issue by Someant** [lincanbin/PHP-PDO-MySQL-Class#2]
I use your code show errow
我检查过数据库权限，发现并没有设置错

**Comment by lincanbin** [comment]
你设置肯定错了，要解决就新建个账户给数据库用。

**Comment by lincanbin** [comment]
https://github.com/lincanbin/PHP-PDO-MySQL-Class/blob/master/demo.php
我写了个Demo，修改数据库连接设置后可以直接跑。

**Comment by Someant** [comment]
谢谢。。恩 明天我试试。。不过今天中午的时候我新建了一个用户还是报同样的错误

**Comment by Someant** [comment]
还是无效
我代码是这么写的
?php

$myusername=NULL;
$errowinfo=NULL;
if($_SERVER['REQUEST_METHOD'] == 'POST')
{
	 $myusername=$_POST['email'];
   		 $mypassword=$_POST['password'];

/*	else
	{
		 $myusername=$_POST['email'];
   		 $mypassword=$_POST['password']; }*/
//require 'config.php';
	define('DBHost', 'localhost');
define('DBName', 'shad');
define('DBUser', 'shad');
define('DBPassword', 'qweqwe');
require(dirname(__FILE__)."/src/PDO.class.php");
$DB = new Db(DBHost, DBName, DBUser, DBPassword);
$tbl_name="user"; // Table name



/*// Connect to server and select databse.
 mysql_connect("$host", "$username", "$password")or die("cannot connect");
 mysql_select_db("$db_name")or die("cannot select DB");







// To protect MySQL injection (more detail about MySQL injection)
 $myusername = stripslashes($myusername);
 $mypassword = stripslashes($mypassword);
 $myusername = mysql_real_escape_string($myusername);
 $mypassword = mysql_real_escape_string($mypassword);

 $sql="SELECT * FROM $tbl_name WHERE email='$myusername' and pass='$mypassword'";
 $result=mysql_query($sql);*/

//pdo
$DB->query("SELECT * FROM $tbl_name WHERE email=? and pass=?", array($myusername,$mypassword));

// Mysql_num_row is counting table row
 $count=mysql_num_rows($DB);

// If result matched $myusername and $mypassword, table row must be 1 row

if($count==1){
echo '登陆成功';

**Comment by lincanbin** [comment]
mysql_num_rows是MySQL的函数，在新版本PHP是已废弃特性，你用这个干嘛？
直接
```php
$count=count($DB->query("SELECT * FROM $tbl_name WHERE email=? and pass=?", array($myusername,$mypassword)));
?>
```
然后demo.php能跑吗？

**Comment by Someant** [comment]
demo可以跑。。

**Comment by Someant** [comment]
$result=$DB->query("SELECT * FROM user WHERE email=?",array($user));

while($row = mysql_fetch_array($result))
  {
	  $vpnuser=$row['vpnuser'];
	  $vpnpass=$row['vpnpass'];
	  $vpnflow=$row['vpnflow'];
	  $sspass=$row['passwd'];
	  $ssflow=$u+$d;
	  $port=$row['port'];
	  $endtime=$row['endtime'];
  }
那读取数据，可以继续这样读么 我试了下好像会出错，用array的方式也是出错的

**Comment by lincanbin** [comment]
你真是旧版mysql写上瘾了
```php
foreach($DB->query("SELECT * FROM user WHERE email=?",array($user)) as $row){
 $vpnuser=$row['vpnuser'];
 $vpnpass=$row['vpnpass'];
 $vpnflow=$row['vpnflow'];
 $sspass=$row['passwd'];
 $ssflow=$u+$d;
 $port=$row['port'];
 $endtime=$row['endtime'];
}
```
如果你只要一行结果，那么只需要这样就可以了
```php
$row = $DB->row("SELECT * FROM user WHERE email=?",array($user));
$ssflow = $u+$d;
```

**Comment by lincanbin** [comment]
https://github.com/lincanbin/Carbon-Forum/blob/master/login.php

你可以看看这个项目，就是用这个PDO类的。
