### ISSUE TITLE
For updates where newvalue = oldvalue, PDOStatement::rowCount() returns zero

### ISSUE THREAD

**Issue by phatnt93** [lincanbin/PHP-PDO-MySQL-Class#21]
When init PDO then add an option (PDO::MYSQL_ATTR_FOUND_ROWS => true) to disable this unexpected behaviour.

Ex: 
$this->pdo = new PDO($dsn,
	$this->DBUser, 
	$this->DBPassword,
	array(
		//For PHP 5.3.6 or lower
		PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8",
		PDO::ATTR_EMULATE_PREPARES => false,

		//长连接
		//PDO::ATTR_PERSISTENT => true,
		
		PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
		PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true,
		PDO::MYSQL_ATTR_FOUND_ROWS => true //Here
	)
);

**Comment by lincanbin** [comment]
Thank you for your feedback.
