### ISSUE TITLE
about where in 

### ISSUE THREAD

**Issue by chainjoy** [lincanbin/PHP-PDO-MySQL-Class#5]
SELECT \* FROM fruit WHERE name IN (apple','banana) AND color = 'red'
how to add "red" ?
$DB->query("SELECT \* FROM fruit WHERE name IN (?) AND color = ? ",array('apple','banana'));

**Comment by lincanbin** [comment]
```php
$DB->query("SELECT * FROM fruit WHERE name IN (?) AND color = ? ", array('apple','banana', 'red'));
```

**Comment by lincanbin** [comment]
看来我设计时还是考虑不周。

**Comment by marcus-hiles** [comment]
@chainjoy, your query should be: 

`$DB->query("SELECT * FROM fruit WHERE name IN (?,?) AND color = ? ",array('apple','banana','red'));`

**Comment by lincanbin** [comment]
In the latest version: 
```php
$DB->query("SELECT * FROM fruit WHERE name IN (:fruit) AND color = :color ",array(
    'fruit' => array('apple','banana'),
    'color' =>'red')
);
```
