### ISSUE TITLE
like is not work

### ISSUE THREAD

**Issue by iscraft** [lincanbin/PHP-PDO-MySQL-Class#6]
PHP>=5.4
$db->query("select * from item where cc like '%,?,%'",[$aid]);
error log:SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty

**Comment by lincanbin** [comment]
```php
$aid = '%your_keyword%'
$db->query("select * from item where cc like ?", [$aid]);
```

**Comment by iscraft** [comment]
so quickly!this is right.i wish the project perfect better,such as count,simple support other sql(like sqlite and pgsql)...thanks!

**Comment by darkworks** [comment]
Like Query this should be added to documentation or main readme file
